### ISSUE TITLE
spamming chat when server is idle

### ISSUE THREAD

**Issue by DrunkMunki** [xNarnia/TCR-TerrariaChatRelay#1]
just setup the bot, joined server, and tested..
once i left, discord kept getting spammed: **left the server...

not sure if this is reading the last message and just repeating every 5mins

![image](https://user-images.githubusercontent.com/865746/82722437-0b1e7280-9d0a-11ea-8ff9-ff7da472877a.png)

**Comment by grandoth** [comment]
I am testing a fix for this. I will submit a pull request if it works.

**Comment by grandoth** [comment]
See PR #2

**Comment by DrunkMunki** [comment]
thanks @grandoth 
I recompiled the DLL and confirmed its no longer spamming chat, thanks :)
For those who can't compile their own, you can download the file DLL here - [https://gamingalliance.net/download/TerrariaChatRelay.zip](https://gamingalliance.net/download/TerrariaChatRelay.zip)

**Comment by xNarnia** [comment]
Thank you very much for fixing this issue @grandoth!
