### ISSUE TITLE
Command shows up on discord and constantly disconnected from discord

### ISSUE THREAD

**Issue by hdseventh** [xNarnia/TCR-TerrariaChatRelay#11]
The command /help show up as a blank message on discord when it shouldn't be sent to discord as it is a command not a message. Tried with v0.9.2 and 0.9.3 with the same result as shown below :
![image](https://user-images.githubusercontent.com/59508429/127781157-842928d9-cdfe-4394-96a0-ce6aee3fbea9.png)

The plugin also often disconnected from Discord and reattempt to connect again and sometimes it shows error "The connection Reset By Peer", is this because of my network problem? i have quite fast internet connection, so i have no clue what caused this.

**Comment by xNarnia** [comment]
Great find on the blank message command bug. This has been resolved. Closing issue.
As per your disconnecting from Discord constantly, that is certainly your network provider. 
I would suggest doing a trace on your network. As well, you can try checking your connection to the gateway below.
wss://gateway.discord.gg/?v=6&encoding=json

If this still becomes an issue for you, please open a brand new issue with this by itself.
Thank you so much!
