### ISSUE TITLE
"." command showing in discord

### ISSUE THREAD

**Issue by Luke1192** [xNarnia/TCR-TerrariaChatRelay#13]
When using . to execute a command in my server it shows in the discord also whenever I type /help it sends a blank message to the discord

**Comment by hdseventh** [comment]
/help blank message should have been fixed in 0.9.4.1

But "." commands is confirmed displayed in discord chat as shown below :
![image](https://user-images.githubusercontent.com/59508429/129085122-6c58837b-e51d-406f-89e1-ed2fbb3a4966.png)

**Comment by Kojirremer** [comment]
Yeah, can confirm. This is kind of a major problem because people (for some reason) using .login instead of /login get their passwords exposed.

**Comment by xNarnia** [comment]
This is now fixed in #17
