### ISSUE TITLE
Embed and Group

### ISSUE THREAD

**Issue by Luke1192** [xNarnia/TCR-TerrariaChatRelay#15]
Can you make it to where whenever you type "help" or execute any command it send's it as an actual embed not the ``` thing.
Also can you make it to where it show's the players group whenever they chat

**Comment by xNarnia** [comment]
Embeds are coming in a future release, important but not priority. Thanks to @hdseventh, group prefix and suffix modifiers in the config file have been added to v.1.0.0.

Thank you!
