### ISSUE TITLE
Command prefix not working

### ISSUE THREAD

**Issue by tsuki-terraria** [xNarnia/TCR-TerrariaChatRelay#18]
**TCR Version:** v1.0.0
**TShock Version:** v4.4.0-pre12 & v4.5.4

Prefix command set to `!` but it can showing the same output when using any prefix. Please see the image bellow.

![image](https://user-images.githubusercontent.com/83478093/134758502-7eb0ee56-344b-48cb-af09-aa3db9a804ca.png)

**Comment by xNarnia** [comment]
Oh, I know exactly why that's happening. What a funny bug, I'll fix it right away!

Thank you for finding this bug. 🙂
