### ISSUE TITLE
Discord command output issue

### ISSUE THREAD

**Issue by tsuki-terraria** [xNarnia/TCR-TerrariaChatRelay#19]
**TCR Version:** v1.0.0
**TShock Version:** v4.4.0-pre12 & v4.5.4

I tried to execute `online` or `playing` command from Discord, and the command output showing the maximum player is 256 while the maximum player from TShock config.json only for 20 players.

![image](https://user-images.githubusercontent.com/83478093/134758880-e5d91d63-37ba-402f-9f83-36f2842b54a3.png)

When there is no player, i tried to execute `online` or `playing` command, it's showing nothing (blank) insted of "No player" message.

![image](https://user-images.githubusercontent.com/83478093/134758926-c0aec0d6-9238-4f1c-acf1-bea7a04f20e0.png)

**Comment by xNarnia** [comment]
Fixed with #21. Thank you for reporting this! Huge thank you to @hdseventh for fixing the issue!
