### ISSUE TITLE
Duplicate discord messages sent after config /reload

### ISSUE THREAD

**Issue by pcider** [xNarnia/TCR-TerrariaChatRelay#27]
Also:
After doing `/reload`, `t!world` command seems to not work, throwing an exception in server console:
![image](https://user-images.githubusercontent.com/28196972/146629870-5203c3d7-fd81-45b9-9db6-41ac7910ada0.png)

**Comment by xNarnia** [comment]
Resolved with 1.4.5 to be released soon
