### ISSUE TITLE
Whilst having multiple Channel_IDs spesified - the commands from one channel text end up in second Channel

### ISSUE THREAD

**Issue by KrystinDix** [xNarnia/TCR-TerrariaChatRelay#29]
Currently, if you have multiple Channel ID's specified it will show something along the following.
Channel ID 1 - (I call this the Console Channel)
User1: t!listadmin
Bot: Administrators for TerrariaChatRelay ...

Channel ID 2 - (I call this the Relay Channel)
Bot: [Discord] <User1> t!listadmin

I would like to hide the messages generated in Channel ID 2 if it is prefixed by the command prefix, as this is undesired messages. Admin users are granted access to the Console channel for running admin commands etc, whilst the Relay channel is for Discord to Terraria chat and vice versa.

**Comment by xNarnia** [comment]
Command input from users no longer relays to other channels and Discord in 1.4.5 to be released soon
