### ISSUE TITLE
"<user> left the server." appears even when a player attempts to connect and fails

### ISSUE THREAD

**Issue by Exeden** [xNarnia/TCR-TerrariaChatRelay#3]
1. Player tries to connect, but fails due to having wrong character type:
```
Output from my server:
85.140.1.61:36365 is connecting... 
85.140.1.61:36365 was booted: Only Non-Journey characters may enter a Non-Journey server. 
```
2. Discord bot sends out a message saying the player Danil left the server, but in reality, he never joined in the first place:
![image](https://user-images.githubusercontent.com/10290610/83414458-932c0880-a3eb-11ea-8c84-aaa5cc1c197f.png)

**Solution:** Feature that Discord bot reports the condition of a player that is leaving the server, with a new setting to turn it off/on based on server admin discretion.

Example 1) Player had journey-mode character and failed.
If setting disabled to show journey-mode failures, no chat is displayed.
If setting enabled to show journey-mode connection failures, the Bot chats out, "USER tried to log on with a journey-mode character".

Example 2) Player tried to log in, but had wrong password.
Bot chats out, "USER password attempt failed."

This solution should also add configurable settings to determine if you want to report this in discord or not.

**Comment by xNarnia** [comment]
Hey there! Thanks for this idea. Are these the only two scenarios you would be interested in seeing developed?

**Comment by xNarnia** [comment]
Closed since the "" has left issue has been fixed and no response from OP.
