### ISSUE TITLE
[TCR-TShock] Duplicate Chat To Discord

### ISSUE THREAD

**Issue by Marcus101RR** [xNarnia/TCR-TerrariaChatRelay#32]
![image](https://user-images.githubusercontent.com/8344293/179570309-21ce7376-562d-4b90-82f2-2684ec99eef5.png)

I take it the Broadcast version of the stream and the chat are getting entangled here. Might be my guess.

**Comment by xNarnia** [comment]
What plugins are you running?

**Comment by xNarnia** [comment]
This issue is resolved with the newest TCR!
