### ISSUE TITLE
Not working on latest Tshock 5 and Terraria

### ISSUE THREAD

**Issue by Ozakinn** [xNarnia/TCR-TerrariaChatRelay#37]
I have the latest Tshock and terraria version. As well as the TCR latest version.
It display an error
![image](https://user-images.githubusercontent.com/21289418/206603339-eba8fcd3-b5c0-4052-b829-0588e7934b4f.png)

**Comment by xNarnia** [comment]
The new updated version is in beta and available for download on the discord. It will be officially released tomorrow or Saturday! 😊

**Comment by Ozakinn** [comment]
alright, Thank you!
