### ISSUE TITLE
Discord support server link is expired

### ISSUE THREAD

**Issue by cheesits456** [xNarnia/TCR-TerrariaChatRelay#4]
I wouldn't mind joining the support server, but, as this issue's title states, the link is expired :P

**Comment by xNarnia** [comment]
The server is no longer supported, sadly. If you're still interested in keeping up with me via Discord, this is my community server that I currently run. Thanks for your patience!

https://discord.gg/jZMfBWa

**Comment by xNarnia** [comment]
I have created a dedicated server due to the increasing interest in TerrariaChatRelay. You can find the link here. 
https://discord.gg/xAQGT4VetN
