### ISSUE TITLE
Broken after 4.4.0 update of TShock

### ISSUE THREAD

**Issue by DrunkMunki** [xNarnia/TCR-TerrariaChatRelay#5]
i get the error below after the update, removing the ChatRelay dll allows the server to start
![image](https://user-images.githubusercontent.com/865746/98863610-bb508500-24bc-11eb-9079-69a2c0822949.png)

**Comment by xNarnia** [comment]
Hi there! I'm going to test it now and see if I can get this resolved. Thanks for your patience!

**Comment by xNarnia** [comment]
Please give this a try and see if there are any further bugs. If it works as intended, I'll finalize it as a release. Thank you!
https://github.com/xPanini/TCR-TerrariaChatRelay-TShock/releases/tag/0.9.1.1.1

**Comment by DrunkMunki** [comment]
confirmed fixed, thanks for your quick response :)
